"""
Loads SLSA v1.2 controls from the structured data embedded here.
Source of truth: dataset/checklist_SLSAv1.2.txt (plain-text) and
frontend/src/data/slsaChecklist.ts (typed IDs).

The data below mirrors both files exactly. Edit domains.py to adjust
domain assignments; edit here only when the SLSA spec itself changes.
"""
from __future__ import annotations

from app.mapping.domains import SLSA_DOMAIN_MAP
from app.mapping.models import SLSAControl

_RAW: list[dict] = [
    # ── Build L1: Provenance Exists ───────────────────────────────────────────
    {
        "id": "l1-sp-1",
        "level": "L1",
        "section": "Software Producer",
        "text": "Follow a consistent build process",
        "description": (
            "Follow a consistent build process so that others can form "
            "expectations about what a 'correct' build looks like."
        ),
    },
    {
        "id": "l1-sp-2",
        "level": "L1",
        "section": "Software Producer",
        "text": "Run builds on a Build L1-compliant platform",
        "description": (
            "Build runs on a hosted build platform on shared or dedicated "
            "infrastructure (e.g. GitHub Actions, Google Cloud Build, Travis CI)."
        ),
    },
    {
        "id": "l1-sp-3",
        "level": "L1",
        "section": "Software Producer",
        "text": "Distribute provenance to consumers",
        "description": "Make provenance available to consumers using ecosystem conventions.",
    },
    {
        "id": "l1-bp-1",
        "level": "L1",
        "section": "Build Platform",
        "text": "Automatically generate provenance",
        "description": (
            "Automatically generate provenance describing how the artifact was "
            "built, including: what entity built the package, what build process "
            "was used, and what the top-level inputs to the build were."
        ),
    },
    {
        "id": "l1-prov-1",
        "level": "L1",
        "section": "Provenance Content",
        "text": "Provenance includes buildDefinition.buildType",
        "description": "Identifies the template used to perform the build.",
    },
    {
        "id": "l1-prov-2",
        "level": "L1",
        "section": "Provenance Content",
        "text": "Provenance includes buildDefinition.externalParameters",
        "description": "All user-controlled inputs to the build must be present.",
    },
    {
        "id": "l1-prov-3",
        "level": "L1",
        "section": "Provenance Content",
        "text": "Provenance includes runDetails.builder.id",
        "description": (
            "URI indicating the transitive closure of the trusted build platform."
        ),
    },

    # ── Build L2: Hosted Build Platform ──────────────────────────────────────
    {
        "id": "l2-sp-1",
        "level": "L2",
        "section": "Software Producer",
        "text": "Run builds on a Build L2-compliant hosted platform",
        "description": "Platform must meet L2 requirements in addition to L1.",
    },
    {
        "id": "l2-sp-2",
        "level": "L2",
        "section": "Software Producer",
        "text": "Distribute signed provenance to consumers",
        "description": (
            "Provenance must be signed and distributed so consumers can validate "
            "authenticity."
        ),
    },
    {
        "id": "l2-bp-1",
        "level": "L2",
        "section": "Build Platform",
        "text": "Platform generates and signs provenance itself",
        "description": (
            "Generate and sign the provenance itself — during the original build, "
            "an after-the-fact reproducible build, or an equivalent system."
        ),
    },
    {
        "id": "l2-bp-2",
        "level": "L2",
        "section": "Build Platform",
        "text": "Provenance generated by control plane, not tenant",
        "description": (
            "The control plane orchestrates each independent build execution and "
            "produces provenance. Tenants must not be able to produce or alter it."
        ),
    },
    {
        "id": "l2-bp-3",
        "level": "L2",
        "section": "Build Platform",
        "text": "Data in provenance sourced directly from build platform",
        "description": (
            "Platform implements security controls to prevent tenant tampering "
            "with provenance data."
        ),
    },
    {
        "id": "l2-con-1",
        "level": "L2",
        "section": "Consumer",
        "text": "Validate provenance authenticity via digital signature",
        "description": (
            "Consumers must verify the provenance is signed with the build "
            "platform's private key before trusting it."
        ),
    },
    {
        "id": "l2-prov-1",
        "level": "L2",
        "section": "Provenance Authenticity",
        "text": "Provenance carries a digital signature from the build platform",
        "description": (
            "Recommended: use signing methods that support transparency logs or "
            "timestamping."
        ),
    },
    {
        "id": "l2-prov-2",
        "level": "L2",
        "section": "Provenance Authenticity",
        "text": "Signing method supports transparency log or timestamping",
        "description": (
            "Enables consumers to verify provenance has not been altered after "
            "the build."
        ),
    },

    # ── Build L3: Hardened Builds ─────────────────────────────────────────────
    {
        "id": "l3-bp-1",
        "level": "L3",
        "section": "Build Platform",
        "text": "Prevent cross-run influence",
        "description": (
            "Prevent runs from influencing one another, even within the same "
            "project."
        ),
    },
    {
        "id": "l3-bp-2",
        "level": "L3",
        "section": "Build Platform",
        "text": "Secret material for signing is inaccessible to user-defined build steps",
        "description": (
            "The secret material used to sign provenance must not be accessible "
            "to user build steps."
        ),
    },
    {
        "id": "l3-bp-3",
        "level": "L3",
        "section": "Build Platform",
        "text": "Every provenance field generated or verified by the build platform",
        "description": (
            "User steps cannot inject or alter any provenance field content "
            "(except L2-permitted exceptions for output artifact names/digests)."
        ),
    },
    {
        "id": "l3-bp-4",
        "level": "L3",
        "section": "Build Platform",
        "text": "Secret material stored in a secure management system",
        "description": (
            "Secret material used to authenticate provenance must be stored in a "
            "secure management system, never in the user build environment."
        ),
    },
    {
        "id": "l3-iso-1",
        "level": "L3",
        "section": "Isolation Strength",
        "text": "Build environment cannot access platform secrets (signing keys, etc.)",
        "description": (
            "Build steps have no access to the platform's signing keys or other "
            "secret material."
        ),
    },
    {
        "id": "l3-iso-2",
        "level": "L3",
        "section": "Isolation Strength",
        "text": "Concurrent builds cannot influence each other's memory",
        "description": "Strong isolation prevents any cross-build memory access.",
    },
    {
        "id": "l3-iso-3",
        "level": "L3",
        "section": "Isolation Strength",
        "text": "Ephemeral build environment provisioned for each build",
        "description": (
            "Previous builds cannot persist environmental changes; a fresh "
            "environment is created per build."
        ),
    },
    {
        "id": "l3-iso-4",
        "level": "L3",
        "section": "Isolation Strength",
        "text": "Cache poisoning is prevented",
        "description": (
            "Output remains identical regardless of cache usage; poisoned cache "
            "entries cannot alter the build result."
        ),
    },
    {
        "id": "l3-iso-5",
        "level": "L3",
        "section": "Isolation Strength",
        "text": "Remote services used during build are captured in externalParameters",
        "description": (
            "Any remote service accessed during the build must be declared in "
            "provenance's externalParameters."
        ),
    },
    {
        "id": "l3-comp-1",
        "level": "L3",
        "section": "Provenance Completeness",
        "text": "externalParameters fully enumerated",
        "description": (
            "All user-controlled inputs to the build are listed completely. "
            "External parameters are untrusted and must be verified downstream."
        ),
    },
    {
        "id": "l3-comp-2",
        "level": "L3",
        "section": "Provenance Completeness",
        "text": "resolvedDependencies captured on best-effort basis",
        "description": (
            "Artifacts needed during build execution are recorded in the "
            "provenance."
        ),
    },
]


def load_slsa_controls() -> list[SLSAControl]:
    controls = []
    for raw in _RAW:
        domains = SLSA_DOMAIN_MAP.get(raw["id"], [])
        controls.append(SLSAControl(domains=domains, **raw))
    return controls
