export interface ChecklistItem {
  id: string
  text: string
  description?: string
}

export interface ChecklistSection {
  title: string
  items: ChecklistItem[]
}

export interface ChecklistLevel {
  level: string
  label: string
  definition: string
  sections: ChecklistSection[]
}

export const slsaChecklist: ChecklistLevel[] = [
  {
    level: 'L1',
    label: 'Build L1 — Provenance Exists',
    definition:
      'Package has provenance showing how it was built. Can be used to prevent mistakes but is trivial to bypass or forge.',
    sections: [
      {
        title: 'Software Producer',
        items: [
          {
            id: 'l1-sp-1',
            text: 'Follow a consistent build process',
            description:
              'Follow a consistent build process so that others can form expectations about what a "correct" build looks like.',
          },
          {
            id: 'l1-sp-2',
            text: 'Run builds on a Build L1-compliant platform',
            description:
              'Build runs on a hosted build platform on shared or dedicated infrastructure (e.g. GitHub Actions, Google Cloud Build, Travis CI).',
          },
          {
            id: 'l1-sp-3',
            text: 'Distribute provenance to consumers',
            description: 'Make provenance available to consumers using ecosystem conventions.',
          },
        ],
      },
      {
        title: 'Build Platform',
        items: [
          {
            id: 'l1-bp-1',
            text: 'Automatically generate provenance',
            description:
              'Automatically generate provenance describing how the artifact was built, including: what entity built the package, what build process was used, and what the top-level inputs to the build were.',
          },
        ],
      },
      {
        title: 'Provenance Content',
        items: [
          {
            id: 'l1-prov-1',
            text: 'Provenance includes buildDefinition.buildType',
            description: 'Identifies the template used to perform the build.',
          },
          {
            id: 'l1-prov-2',
            text: 'Provenance includes buildDefinition.externalParameters',
            description: 'User-controlled inputs to the build must be present.',
          },
          {
            id: 'l1-prov-3',
            text: 'Provenance includes runDetails.builder.id',
            description:
              'URI indicating the transitive closure of the trusted build platform.',
          },
        ],
      },
    ],
  },
  {
    level: 'L2',
    label: 'Build L2 — Hosted Build Platform',
    definition:
      'Forging the provenance or evading verification requires an explicit attack, though this may be easy to perform. Deters unsophisticated adversaries or those who face legal or financial risk.',
    sections: [
      {
        title: 'Software Producer',
        items: [
          {
            id: 'l2-sp-1',
            text: 'Run builds on a Build L2-compliant hosted platform',
            description:
              'Platform must meet L2 requirements in addition to L1.',
          },
          {
            id: 'l2-sp-2',
            text: 'Distribute signed provenance to consumers',
            description:
              'Provenance must be signed and distributed so consumers can validate authenticity.',
          },
        ],
      },
      {
        title: 'Build Platform',
        items: [
          {
            id: 'l2-bp-1',
            text: 'Platform generates and signs provenance itself',
            description:
              'Generate and sign the provenance itself — during the original build, an after-the-fact reproducible build, or an equivalent system.',
          },
          {
            id: 'l2-bp-2',
            text: 'Provenance generated by control plane, not tenant',
            description:
              'The control plane orchestrates each independent build execution and produces provenance. Tenants must not be able to produce or alter provenance.',
          },
          {
            id: 'l2-bp-3',
            text: 'Data in provenance sourced directly from build platform',
            description:
              'Platform implements security controls to prevent tenant tampering with provenance data.',
          },
        ],
      },
      {
        title: 'Consumer',
        items: [
          {
            id: 'l2-con-1',
            text: 'Validate provenance authenticity via digital signature',
            description:
              'Consumers must verify the provenance is signed with the build platform\'s private key before trusting it.',
          },
        ],
      },
      {
        title: 'Provenance Authenticity',
        items: [
          {
            id: 'l2-prov-1',
            text: 'Provenance carries a digital signature from the build platform',
            description:
              'Recommended: use signing methods that support transparency logs or timestamping.',
          },
          {
            id: 'l2-prov-2',
            text: 'Signing method supports transparency log or timestamping',
            description:
              'Enables consumers to verify provenance has not been altered after the build.',
          },
        ],
      },
    ],
  },
  {
    level: 'L3',
    label: 'Build L3 — Hardened Builds',
    definition:
      'Forging the provenance or evading verification requires exploiting a vulnerability that is beyond the capabilities of most adversaries.',
    sections: [
      {
        title: 'Build Platform',
        items: [
          {
            id: 'l3-bp-1',
            text: 'Prevent cross-run influence',
            description:
              'Prevent runs from influencing one another, even within the same project.',
          },
          {
            id: 'l3-bp-2',
            text: 'Secret material for signing is inaccessible to user-defined build steps',
            description:
              'The secret material used to sign provenance must not be accessible to user build steps.',
          },
          {
            id: 'l3-bp-3',
            text: 'Every provenance field generated or verified by the build platform',
            description:
              'User steps cannot inject or alter any provenance field content (except the L2-permitted exceptions for output artifact names/digests).',
          },
          {
            id: 'l3-bp-4',
            text: 'Secret material stored in a secure management system',
            description:
              'Secret material used to authenticate provenance must be stored in a secure management system, never in the user build environment.',
          },
        ],
      },
      {
        title: 'Isolation Strength',
        items: [
          {
            id: 'l3-iso-1',
            text: 'Build environment cannot access platform secrets (signing keys, etc.)',
            description:
              'Build steps have no access to the platform\'s signing keys or other secret material.',
          },
          {
            id: 'l3-iso-2',
            text: 'Concurrent builds cannot influence each other\'s memory',
            description:
              'Strong isolation prevents any cross-build memory access.',
          },
          {
            id: 'l3-iso-3',
            text: 'Ephemeral build environment provisioned for each build',
            description:
              'Previous builds cannot persist environmental changes; a fresh environment is created per build.',
          },
          {
            id: 'l3-iso-4',
            text: 'Cache poisoning is prevented',
            description:
              'Output remains identical regardless of cache usage; poisoned cache entries cannot alter the build result.',
          },
          {
            id: 'l3-iso-5',
            text: 'Remote services used during build are captured in externalParameters',
            description:
              'Any remote service accessed during the build must be declared in provenance\'s externalParameters.',
          },
        ],
      },
      {
        title: 'Provenance Completeness',
        items: [
          {
            id: 'l3-comp-1',
            text: 'externalParameters fully enumerated',
            description:
              'All user-controlled inputs to the build are listed completely in the provenance at L3. External parameters are untrusted and must be included and verified downstream.',
          },
          {
            id: 'l3-comp-2',
            text: 'resolvedDependencies captured on best-effort basis',
            description:
              'Artifacts needed during build execution are recorded in the provenance.',
          },
        ],
      },
    ],
  },
]
