-- =====================================================================
-- SQLite schema: User Management
-- Target: SQLite 3.35+ (uses STRICT tables, generated cols, JSON1 ok)
-- Enable foreign keys per-connection: PRAGMA foreign_keys = ON;
--
-- Session model
-- ──────────────────────────────────────────────────────────────────
--   Authentication uses short-lived JWT tokens (60 min) stored in
--   HttpOnly, Secure, SameSite=Strict cookies named `cm_token`.
--   A companion readable cookie `cm_present` (non-HttpOnly) lets the
--   frontend skip the /api/auth/me call when no session exists.
--   The `sessions` table records active sessions and is used to bulk-
--   revoke all sessions on password change.
--
-- RBAC model
-- ──────────────────────────────────────────────────────────────────
--   Users ──► user_roles  ──► roles   (direct role assignment)
--   Users ──► user_groups ──► groups
--             groups      ──► group_roles ──► roles  (indirect)
--
--   Effective permissions for a user =
--       their direct roles
--     ∪ the roles of every group they belong to
--
--   Only users with the 'admin' role may access /api/admin/* endpoints
--   and the Administration section of the UI.
-- =====================================================================

PRAGMA foreign_keys = ON;
PRAGMA journal_mode  = WAL;

-- ---------------------------------------------------------------------
-- 1. users
--    Core identity record. Passwords are NEVER stored in plain text —
--    only a bcrypt hash produced at the app layer.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id              TEXT    PRIMARY KEY,                       -- UUIDv4 (generated by app)
    first_name      TEXT    NOT NULL CHECK (length(first_name) BETWEEN 1 AND 100),
    last_name       TEXT    NOT NULL CHECK (length(last_name)  BETWEEN 1 AND 100),
    email           TEXT    NOT NULL,
    email_lower     TEXT    GENERATED ALWAYS AS (lower(email)) VIRTUAL,
    mobile_number   TEXT    CHECK (mobile_number IS NULL
                                   OR mobile_number GLOB '+[0-9]*'),   -- E.164-ish
    password_hash   TEXT    NOT NULL,                          -- bcrypt output
    email_verified  INTEGER NOT NULL DEFAULT 0 CHECK (email_verified  IN (0,1)),
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active       IN (0,1)),
    api_access      INTEGER NOT NULL DEFAULT 1 CHECK (api_access      IN (0,1)),
    last_login_at   TEXT,                                      -- ISO-8601 UTC
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

-- Case-insensitive uniqueness on email
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower ON users(email_lower);
CREATE INDEX        IF NOT EXISTS ix_users_active      ON users(is_active);

CREATE TRIGGER IF NOT EXISTS trg_users_updated_at
AFTER UPDATE ON users FOR EACH ROW
BEGIN
    UPDATE users SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
    WHERE id = OLD.id;
END;

-- ---------------------------------------------------------------------
-- 2. roles  (lookup table — SQLite has no ENUM)
--    Shared by both direct user-role assignments AND group-role assignments.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT    NOT NULL UNIQUE CHECK (length(name) BETWEEN 1 AND 100),
    description TEXT
) STRICT;

INSERT OR IGNORE INTO roles (name, description) VALUES
    ('admin',     'Full administrative access'),
    ('moderator', 'Content moderation rights'),
    ('user',      'Standard end user');

-- ---------------------------------------------------------------------
-- 3. user_roles  (direct user → role assignment)
--    Keep roles OUT of the users row to prevent privilege escalation
--    via a single-column UPDATE.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_roles (
    user_id     TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id     INTEGER NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    granted_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    granted_by  TEXT             REFERENCES users(id) ON DELETE SET NULL,
    PRIMARY KEY (user_id, role_id)
) STRICT;

CREATE INDEX IF NOT EXISTS ix_user_roles_role ON user_roles(role_id);

-- ---------------------------------------------------------------------
-- 4. groups
--    Named collections of users.  A group accumulates roles through
--    group_roles; every member inherits those roles automatically.
--    App layer enforces: name must be lowercase alphanumeric (a-z, 0-9).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS groups (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT    NOT NULL UNIQUE CHECK (length(name) BETWEEN 1 AND 100),
    description TEXT,
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX IF NOT EXISTS ix_groups_name ON groups(name);

CREATE TRIGGER IF NOT EXISTS trg_groups_updated_at
AFTER UPDATE ON groups FOR EACH ROW
BEGIN
    UPDATE groups SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
    WHERE id = OLD.id;
END;

INSERT OR IGNORE INTO groups (name, description) VALUES
    ('administrators', 'Platform administrators'),
    ('staff',          'Internal staff members'),
    ('apiclients',     'Service accounts with API access');

-- ---------------------------------------------------------------------
-- 5. group_roles  (group → role assignment)
--    All members of a group inherit these roles.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS group_roles (
    group_id    INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    role_id     INTEGER NOT NULL REFERENCES roles(id)  ON DELETE RESTRICT,
    granted_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    granted_by  TEXT             REFERENCES users(id)  ON DELETE SET NULL,
    PRIMARY KEY (group_id, role_id)
) STRICT;

CREATE INDEX IF NOT EXISTS ix_group_roles_role  ON group_roles(role_id);
CREATE INDEX IF NOT EXISTS ix_group_roles_group ON group_roles(group_id);

-- ---------------------------------------------------------------------
-- 6. user_groups  (user → group membership)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_groups (
    user_id     TEXT    NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    group_id    INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    joined_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    added_by    TEXT             REFERENCES users(id)  ON DELETE SET NULL,
    PRIMARY KEY (user_id, group_id)
) STRICT;

CREATE INDEX IF NOT EXISTS ix_user_groups_group ON user_groups(group_id);
CREATE INDEX IF NOT EXISTS ix_user_groups_user  ON user_groups(user_id);

-- ---------------------------------------------------------------------
-- 7. sessions  (server-side session store)
--    Tracks active JWT sessions per user.
--    token_hash stores a bcrypt hash of the raw JWT for revocation checks.
--    revoked_at is set (bulk) when a user changes their password, ensuring
--    all prior sessions are invalidated regardless of token expiry.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
    id          TEXT PRIMARY KEY,                              -- UUIDv4
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL,                                 -- bcrypt hash of JWT
    user_agent  TEXT,
    ip_address  TEXT,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    expires_at  TEXT NOT NULL,                                 -- ISO-8601 UTC
    revoked_at  TEXT                                           -- NULL = active
) STRICT;

CREATE INDEX IF NOT EXISTS ix_sessions_user    ON sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_expires ON sessions(expires_at);

-- ---------------------------------------------------------------------
-- 8. auth_tokens  (single-use tokens for password-reset & email-verify)
--    password_reset: generated by an admin via POST /api/admin/users/{id}/reset-password.
--                    A bcrypt-hashed token is stored here; the raw token is
--                    sent to the user's email (requires SMTP configuration).
--                    Tokens expire after 24 hours and are consumed on use.
--    email_verify:   reserved for future email verification flow.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_tokens (
    id          TEXT PRIMARY KEY,                              -- UUIDv4
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose     TEXT NOT NULL CHECK (purpose IN ('password_reset','email_verify')),
    token_hash  TEXT NOT NULL,                                 -- bcrypt hash of raw token
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    expires_at  TEXT NOT NULL,                                 -- 24 h from creation
    consumed_at TEXT                                           -- NULL = not yet used
) STRICT;

CREATE INDEX IF NOT EXISTS ix_auth_tokens_user ON auth_tokens(user_id, purpose);

-- ---------------------------------------------------------------------
-- 9. audit_log  (immutable record of every privileged action)
--    Covers users, groups, role assignments, and auth events.
--    action vocabulary (non-exhaustive):
--      user.*   : user.create        user.update        user.delete
--                 user.enable        user.disable
--                 user.login
--                 user.password_change                   -- self-service via Settings page
--                 user.password_reset                    -- admin-initiated via User Management
--                 user.api_grant     user.api_revoke
--      role.*   : role.create        role.update        role.delete
--                 role.grant         role.revoke
--      group.*  : group.create       group.update       group.delete
--                 group.role_grant   group.role_revoke
--                 group.member_add   group.member_remove
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    actor_id   TEXT    REFERENCES users(id) ON DELETE SET NULL,
    action     TEXT    NOT NULL,
    target_id  TEXT,                                           -- user/group/role id
    metadata   TEXT,                                           -- JSON blob
    created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX IF NOT EXISTS ix_audit_target ON audit_log(target_id);
CREATE INDEX IF NOT EXISTS ix_audit_actor  ON audit_log(actor_id);
CREATE INDEX IF NOT EXISTS ix_audit_action ON audit_log(action);

-- ---------------------------------------------------------------------
-- 10. app_settings  (key/value store for application-level configuration)
--     Authentication settings live here under the 'auth.*' namespace.
--     Managed via Administration → Authentication in the UI (admin only).
--     Key vocabulary:
--       auth.signup_enabled        : 'true' | 'false'
--       auth.min_password_length   : integer string, default '8'
--       auth.require_number        : 'true' | 'false'
--       auth.require_uppercase     : 'true' | 'false'
--       auth.require_special_char  : 'true' | 'false'
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
) STRICT;

-- Default authentication settings
INSERT OR IGNORE INTO app_settings (key, value) VALUES
    ('auth.signup_enabled',       'true'),
    ('auth.min_password_length',  '8'),
    ('auth.require_number',       'false'),
    ('auth.require_uppercase',    'false'),
    ('auth.require_special_char', 'false');

-- ---------------------------------------------------------------------
-- Helper view: effective_user_roles
--   Returns every role a user holds, whether direct or via a group.
--   Used by the backend RBAC layer (app/dependencies.py) to determine
--   whether a user has the 'admin' role.
--   Use in application queries; not a substitute for app-layer enforcement.
-- ---------------------------------------------------------------------
CREATE VIEW IF NOT EXISTS effective_user_roles AS
-- direct assignments
SELECT ur.user_id,
       r.id   AS role_id,
       r.name AS role_name,
       'direct' AS source,
       NULL   AS group_id,
       NULL   AS group_name
FROM   user_roles ur
JOIN   roles r ON r.id = ur.role_id
UNION
-- indirect via group membership
SELECT ug.user_id,
       r.id   AS role_id,
       r.name AS role_name,
       'group' AS source,
       g.id   AS group_id,
       g.name AS group_name
FROM   user_groups ug
JOIN   groups      g  ON g.id  = ug.group_id
JOIN   group_roles gr ON gr.group_id = g.id
JOIN   roles       r  ON r.id  = gr.role_id;
